// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const getStudent = `-- name: GetStudent :one
SELECT id FROM students
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStudent(ctx context.Context, id sql.NullInt32) (sql.NullInt32, error) {
	row := q.db.QueryRowContext(ctx, getStudent, id)
	err := row.Scan(&id)
	return id, err
}
